# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gauss_kce_cpp <- function(x, Xi, deriv, x_fix, Xi_fix, h) {
    .Call(`_aftNested_gauss_kce`, x, Xi, deriv, x_fix, Xi_fix, h)
}

.triweight_kce_cpp <- function(x, Xi, deriv, x_fix, Xi_fix, h) {
    .Call(`_aftNested_triweight_kce`, x, Xi, deriv, x_fix, Xi_fix, h)
}

order_cpp <- function(x) {
    .Call(`_aftNested_order_`, x)
}

